### ISSUE TITLE
US 6:  Crear Wireframe del Carrito de Compras

### ISSUE THREAD

**Issue by lionel1014** [lionel1014/grupo_1_batitienda#6]
## *Descripción:* 
 Como equipo, necesitamos crear un wireframe de la página de carrito de compras para comprender la estructura

## *Criterios de Aceptación:* 
- [ ] Debe crearse un wireframe (digital o analógico) de la página de carrito de compras.
- [ ] El wireframe debe representar la estructura y los componentes de la página de carrito de compras de manera clara.

**Comment by EM-Informatica** [comment]
![image](https://github.com/lionel1014/grupo_1_batitienda/assets/146139832/f4a319ac-5b06-4e07-9abb-3bed2ba6cc84)

**Comment by EM-Informatica** [comment]
![image](https://github.com/lionel1014/grupo_1_batitienda/assets/146139832/b264c7b7-3229-43cd-a055-8718ace5c81c)

**Comment by EM-Informatica** [comment]
![image](https://github.com/lionel1014/grupo_1_batitienda/assets/146139832/3d1f9cb4-74a1-40a8-92dd-0fd8a781bc6b)
